version: '2'
services:
  wordpress:
    image: wordpress:latest
    links:
     - db
    ports:
     - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: example
    restart: always
  
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
  
