version: '2'
services:
  worker:
    image: tutum/hello-world
    container_name: logger
    command: sh -c "while true; do echo test; done "
    logging: 
      # forward logs to sys log
      driver: syslog
      options:
         syslog-address: "udp://logs5.papertrailapp.com:30380"
      # driver: json-file
      # options:
       # max-file: "5"
        # max-size: "1m"
