version: '2'
services:
  wordpress:
    image: wordpress:latest
    depends_on: 
       - db
    links:
       - db
    ports:
       - 8080:80
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    networks:
      - frontend
    restart: always

  db:
    image: mariadb
    volumes:
       - "./volumes/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
